# Default values for rest-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: maxxx873/dsp-eml-prj-rest
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

env:
  - name: PORT
    value: "8088"
  - name: KEYCLOAK_JWT_SET_URI
    value: "http://keycloak-service:9080/realms/master/protocol/openid-connect/certs"
  - name: KEYCLOAK_REALM_ISSUER_URL
    value: "http://keycloak-service:9080/realms/master"
  - name: KEYCLOAK_SERVER_URL
    value: "http://keycloak-service:9080"
  - name: KEYCLOAK_SERVER_REALM
    value: "master"
  - name: KEYCLOAK_SERVER_USERNAME
    value: "admin"
  - name: KEYCLOAK_SERVER_PASSWORD
    value: "admin"
  - name: MAIL_SERVER_BASE_URL
    value: "http://james-admin:8000"
  - name: MONGODB_HOST
    value: "mongodb"
  - name: MONGODB_PORT
    value: "27017"
  - name: ELASTICSEARCH_URIS
    value: "http://elasticsearch:9200"
  - name: ELASTICSEARCH_ENDPOINTS
    value: "elasticsearch:9200"
  - name: ELASTICSEARCH_USERNAME
    value: "elastic"
  - name: ELASTICSEARCH_PASSWORD
    value: "secret"
  - name: RABBITMQ_HOST
    value: "rabbitmq"
  - name: RABBITMQ_PORT
    value: "5672"
  - name: RABBITMQ_USERNAME
    value: "guest"
  - name: RABBITMQ_PASSWORD
    value: "guest"
  - name: CRYPTO_PASSWORD
    value: "pass"
  - name: CRYPTO_SALT
    value: "e707efd5cf9f191d"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: NodePort
  port: 8088
  nodePort: 30039

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
