version: '3'

services:

  james:
    depends_on:
      - elasticsearch
      - cassandra
      - tika
      - rabbitmq
      - s3
    image: apache/james:distributed-latest
    container_name: james-distributed
    hostname: james.local
    ports:
      - "80:80"
      - "25:25"
      - "110:110"
      - "143:143"
      - "465:465"
      - "587:587"
      - "993:993"
      - "8000:8000"
    volumes:
      - ./conf/:/root/conf/
      - ./extensions-jars/:/root/extensions-jars/
    networks:
      - james

  elasticsearch:
    image: blacktop/elasticsearch:7.10.2
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
    networks:
      - james

  elastichq:
    image: elastichq/elasticsearch-hq
    ports:
      - "5000:5000"
    environment:
      - HQ_DEFAULT_URL=http://elasticsearch:9200
    networks:
      - james

  kibana:
    image: blacktop/kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - james

  cassandra:
    image: cassandra:3.11.10
    ports:
      - "9042:9042"
    networks:
      - james

  tika:
    image: apache/tika:1.28.2

  rabbitmq:
    image: rabbitmq:3.9.18-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - james

  s3:
    image: zenko/cloudserver:8.2.6
    container_name: s3.docker.test
    environment:
      - SCALITY_ACCESS_KEY_ID=accessKey1
      - SCALITY_SECRET_ACCESS_KEY=secretKey1
      - S3BACKEND=mem
      - LOG_LEVEL=trace
      - REMOTE_MANAGEMENT_DISABLE=1
    networks:
      - james

  keycloak:
    image: quay.io/keycloak/keycloak:20.0.1
    command: [ 'start-dev --import-realm' ]
    volumes:
      - ./realm-config:/opt/keycloak/data/import
    environment:
      - KC_DB=dev-file
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_FEATURES=scripts
      - KC_HTTP_PORT=9080
      - KC_HTTPS_PORT=9443
    ports:
      - 127.0.0.1:9080:9080
      - 127.0.0.1:9443:9443

networks:
  james:
    driver: bridge