kind: Service
apiVersion: v1
metadata:
  name: james-smtp-ssl
spec:
  selector:
    app.kubernetes.io/instance: james
    app.kubernetes.io/name: james-chart
  ports:
    - protocol: TCP
      port: 10465
      name: "smtp-ssl"
---
apiVersion: v1
kind: Service
metadata:
  name: james-imap-ssl
spec:
  selector:
    app.kubernetes.io/instance: james
    app.kubernetes.io/name: james-chart
  ports:
    - protocol: TCP
      port: 10993
      name : "imap-ssl"
---
kind: Service
apiVersion: v1
metadata:
  name: james-admin
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: james
    app.kubernetes.io/name: james-chart
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      name: "web"
---
kind: Service
apiVersion: v1
metadata:
  name: jmap
spec:
  selector:
    instance: james-jmap
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: "james-jmap"
---
kind: Service
apiVersion: v1
metadata:
  name: james
spec:
  selector:
    instance: james-imap-smtp
  ports:
    - protocol: TCP
      port: 25
      targetPort: 25
      name: "smtp-open"
---
kind: Service
apiVersion: v1
metadata:
  name: james-smtp
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/instance: james
    app.kubernetes.io/name: james-chart
  ports:
    - protocol: TCP
      port: 1025
      targetPort: 1025
      name: "james-smtp"
---
kind: Service
apiVersion: v1
metadata:
  name: imap
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/instance: james
    app.kubernetes.io/name: james-chart
  ports:
    - protocol: TCP
      port: 10143
      targetPort: 10143
      name: "james-imap"
---
kind: Service
apiVersion: v1
metadata:
  name: james-smtp-auth
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/instance: james
    app.kubernetes.io/name: james-chart
  ports:
    - protocol: TCP
      port: 10587
      targetPort: 10587
      name: "james-smtp-auth"
