kind: Service
apiVersion: v1
metadata:
  name: james-client
spec:
  selector:
    instance: james-imap-smtp
  type: NodePort
  ports:
    - protocol: TCP
      port: 465
      name: "smtp-ssl"
---
apiVersion: v1
kind: Service
metadata:
  name: james-imap
spec:
  type: NodePort
  selector:
    instance: james-imap-smtp
  ports:
    - protocol: TCP
      port: 993
      name : "imap-ssl"
---
kind: Service
apiVersion: v1
metadata:
  name: james-admin
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: james
    app.kubernetes.io/name: james-chart
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      name: "web"
---
kind: Service
apiVersion: v1
metadata:
  name: jmap
spec:
  selector:
    instance: james-jmap
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: "james-jmap"
---
kind: Service
apiVersion: v1
metadata:
  name: james
spec:
  selector:
    instance: james-imap-smtp
  ports:
    - protocol: TCP
      port: 25
      targetPort: 25
      name: "smtp-open"
