server:
  port: ${PORT:8088}

authorization:
  service: ${AUTHORIZATION_SERVICE:keycloak}


spring:
  output:
    ansi:
      enabled: always

  config:
    import: optional:.env[.properties]
  main:
    allow-bean-definition-overriding: true

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    listener:
      simple:
        prefetch: 1
      direct:
        prefetch: 1

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_JWT_SET_URI}
          issuer-uri: ${KEYCLOAK_REALM_ISSUER_URL}
    password: ${CRYPTO_PASSWORD:pass}
    salt: ${CRYPTO_SALT:e707efd5cf9f191d}

  data:
    mongodb:
      host: ${MONGODB_HOST}
      port: ${MONGODB_PORT}
      database: disposableemail
      auto-index-creation: true

    elasticsearch:
      rest:
        uris: ${ELASTICSEARCH_URIS:http://localhost:9200}
      client:
        reactive:
          endpoints: ${ELASTICSEARCH_ENDPOINTS:localhost:9200}
          max-in-memory-size: 512MB

keycloak:
  server:
    url: ${KEYCLOAK_SERVER_URL}
    realm: ${KEYCLOAK_SERVER_REALM}
    username: ${KEYCLOAK_SERVER_USERNAME}
    password: ${KEYCLOAK_SERVER_PASSWORD}
    client: ${KEYCLOAK_SERVER_CLIENT:admin-cli}

mail-server:
  name: ${MAIL_SERVER_NAME:Apache James}
  mailbox: ${MAILBOX_NAME:INBOX}
  base-url: ${MAIL_SERVER_BASE_URL}
  defaultUserSizeQuota: ${DEFAULT_USER_SIZE_QUOTA}
  quotaPath: ${QUOTA_PATH:/quota/users/}

exchanges:
  messages: DisposableEmail-exchange-messages
  accounts: DisposableEmail-exchange-accounts

routing-keys:
  messages-getting: getting-messages-key
  account-start-creating: account-start-creating-key
  account-auth-confirmation: account-auth-confirmation-key
  account-in-mail-service-creating: account-in-mail-service-creating-key
  account-mailbox-in-mail-service-creating: account-mailbox-creating-key
  account-quota-in-mail-service-updating: account-quota-in-mail-service-updating-key

queues:
  messages-getting: DisposableEmail-queue-messages
  account-start-creating: DisposableEmail-queue-account-start-creating
  account-auth-confirmation: DisposableEmail-queue-account-auth-confirmation
  account-in-mail-service-creating: DisposableEmail-queue-account-in-mail-service-creating
  account-mailbox-in-mail-service-creating: DisposableEmail-queue-account-mailbox-creating
  account-quota-in-mail-service-updating: DisposableEmail-queue-account-quota-in-mail-service-updating

logging:
  level.root: info

resilience4j.retry:
  instances:
    retryAuthorizationService:
      maxAttempts: 15
      waitDuration: 5s
      retryExceptions:
        - org.springframework.web.client.HttpServerErrorException
    retryMailService:
      maxAttempts: 15
      waitDuration: 3s