spring:
  application:
    name: disposable-email-project-API
  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:27017}
      database: disposableemail
  mongodb:
    embedded:
      version: 3.4.6

server:
  port: ${PORT:8088}

authorization:
  service: ${AUTHORIZATION_SERVICE:keycloak}

