server:
  port: ${PORT:8088}

spring:
  main:
    allow-bean-definition-overriding: true

  data:
    mongodb:
      host: localhost
      port: 0
      database: disposableemail
      auto-index-creation: true

  mongodb:
    embedded:
      version: 4.4.0

logging:
  level.root: info
