openapi: 3.0.3
components:
  responses:
    '200':
      description: Account collection
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '../schemas/schemas.yaml#/components/schemas/Account'
    '404':
      description: Accounts not found
      content:
        application/json:
          schema:
            $ref: '../schemas/schemas.yaml#/components/schemas/ErrorResponse'