openapi: 3.0.3
info:
  title: disposable-email-project
  description: 'Disposable Email Project API'
  version: 0.0.1
servers:
  - url: /
    description: ''
paths:
  /accounts:
    post:
      operationId: postAccountCollection
      responses:
        '201':
          description: Account resource created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account-account.read'
          links:
            GetAccountItem:
              operationId: getAccountItem
              parameters:
                id: $response.body#/id
              description: The `id` value returned in the response can be used as the `id` parameter in `GET /accounts/{id}`.
        '400':
          description: Invalid input
        '422':
          description: Unprocessable entity
      summary: Creates a Account resource.
      description: Creates a Account resource.
      parameters: []
      requestBody:
        description: The new Account resource
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Account-account.write'
        required: true
      deprecated: false
    parameters: []
  /accounts/{id}:
    get:
      operationId: getAccountItem
      responses:
        '200':
          description: Account resource
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account-account.read'
        '404':
          description: Resource not found
      summary: Retrieves a Account resource.
      description: Retrieves a Account resource.
      parameters:
        - name: id
          in: path
          description: Resource identifier
          required: true
          deprecated: false
          allowEmptyValue: false
          schema:
            type: string
          style: simple
          explode: false
          allowReserved: false
      deprecated: false
    delete:
      operationId: deleteAccountItem
      responses:
        '204':
          description: Account resource deleted
        '404':
          description: Resource not found
      summary: Removes the Account resource.
      description: Removes the Account resource.
      parameters:
        - name: id
          in: path
          description: Resource identifier
          required: true
          deprecated: false
          allowEmptyValue: false
          schema:
            type: string
          style: simple
          explode: false
          allowReserved: false
      deprecated: false
    parameters: []
  /domains:
    get:
      operationId: getDomainCollection
      responses:
        '200':
          description: Domain collection
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Domain'
      summary: Retrieves the collection of Domain resources.
      description: Retrieves the collection of Domain resources.
      parameters:
        - name: page
          in: query
          description: The collection page number
          required: false
          deprecated: false
          allowEmptyValue: true
          schema:
            type: integer
            default: 1
          style: form
          explode: false
          allowReserved: false
      deprecated: false
    parameters: []
  /domains/{id}:
    get:
      operationId: getDomainItem
      responses:
        '200':
          description: Domain resource
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Domain'
        '404':
          description: Resource not found
      summary: Retrieves a Domain resource.
      description: Retrieves a Domain resource.
      parameters:
        - name: id
          in: path
          description: Resource identifier
          required: true
          deprecated: false
          allowEmptyValue: false
          schema:
            type: string
          style: simple
          explode: false
          allowReserved: false
      deprecated: false
    parameters: []
  /me:
    get:
      operationId: get_meAccountItem
      responses:
        '200':
          description: Account resource
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account-account.read'
        '404':
          description: Resource not found
      summary: Retrieves a Account resource.
      description: Retrieves a Account resource.
      parameters: []
      deprecated: false
    parameters: []
  /messages:
    get:
      operationId: getMessageCollection
      responses:
        '200':
          description: Message collection
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Message-messages.read'
      summary: Retrieves the collection of Message resources.
      description: Retrieves the collection of Message resources.
      parameters:
        - name: page
          in: query
          description: The collection page number
          required: false
          deprecated: false
          allowEmptyValue: true
          schema:
            type: integer
            default: 1
          style: form
          explode: false
          allowReserved: false
      deprecated: false
    parameters: []
  /messages/{id}:
    get:
      operationId: getMessageItem
      responses:
        '200':
          description: Message resource
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message-message.read'
        '404':
          description: Resource not found
      summary: Retrieves a Message resource.
      description: Retrieves a Message resource.
      parameters:
        - name: id
          in: path
          description: Resource identifier
          required: true
          deprecated: false
          allowEmptyValue: false
          schema:
            type: string
          style: simple
          explode: false
          allowReserved: false
      deprecated: false
    delete:
      operationId: deleteMessageItem
      responses:
        '204':
          description: Message resource deleted
        '404':
          description: Resource not found
      summary: Removes the Message resource.
      description: Removes the Message resource.
      parameters:
        - name: id
          in: path
          description: Resource identifier
          required: true
          deprecated: false
          allowEmptyValue: false
          schema:
            type: string
          style: simple
          explode: false
          allowReserved: false
      deprecated: false
    patch:
      operationId: patchMessageItem
      responses:
        '200':
          description: Message resource updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message-message.write'
          links:
            GetMessageItem:
              operationId: getMessageItem
              parameters:
                id: $response.body#/id
              description: The `id` value returned in the response can be used as the `id` parameter in `GET /messages/{id}`.
        '400':
          description: Invalid input
        '404':
          description: Resource not found
        '422':
          description: Unprocessable entity
      summary: Updates the Message resource.
      description: Updates the Message resource.
      parameters:
        - name: id
          in: path
          description: Resource identifier
          required: true
          deprecated: false
          allowEmptyValue: false
          schema:
            type: string
          style: simple
          explode: false
          allowReserved: false
      requestBody:
        description: The updated Message resource
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Message-message.write'
        required: true
      deprecated: false
    parameters: []
  /sources/{id}:
    get:
      operationId: getSourceItem
      responses:
        '200':
          description: Source resource
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Source-source.read'
        '404':
          description: Resource not found
      summary: Retrieves a Source resource.
      description: Retrieves a Source resource.
      parameters:
        - name: id
          in: path
          description: Resource identifier
          required: true
          deprecated: false
          allowEmptyValue: false
          schema:
            type: string
          style: simple
          explode: false
          allowReserved: false
      deprecated: false
    parameters: []
  /token:
    post:
      operationId: postCredentialsItem
      responses:
        '200':
          description: Get JWT token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Token'
      summary: Get JWT token to login.
      description: ''
      parameters: []
      requestBody:
        description: Generate new JWT Token
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Credentials'
        required: false
      deprecated: false
    parameters: []
components:
  schemas:
    Account-account.read:
      type: object
      description: ''
      properties:
        id:
          readOnly: true
          type: string
        address:
          format: email
          externalDocs:
            url: https://schema.org/email
          type: string
        quota:
          type: integer
        used:
          type: integer
        isDisabled:
          type: boolean
        isDeleted:
          type: boolean
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
      required:
        - address
    Account-account.write:
      type: object
      description: ''
      properties:
        id:
          readOnly: true
          type: string
        address:
          format: email
          externalDocs:
            url: https://schema.org/email
          type: string
        password:
          type: string
      required:
        - address
        - password
    Domain:
      type: object
      description: ''
      properties:
        id:
          readOnly: true
          type: string
        domain:
          type: string
        isActive:
          type: boolean
        isPrivate:
          type: boolean
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    Message-message.read:
      type: object
      description: ''
      properties:
        id:
          readOnly: true
          type: string
        accountId:
          readOnly: true
          type: string
          format: iri-reference
        msgid:
          readOnly: true
          type: string
        from:
          example:
            address: from@example.com
            name: John Doe
          readOnly: true
          externalDocs:
            url: https://schema.org/sender
          type: array
          items:
            type: string
          nullable: true
        to:
          type: array
          items:
            type: array
            items:
              example:
                  address: receiver@example.com
                  name: John Doe
              readOnly: true
              externalDocs:
                url: https://schema.org/recipient
              nullable: true
        cc:
          type: array
          items:
            type: array
            items:
              example:
                - address: cc@example.com
                  name: John Doe
              readOnly: true
              externalDocs:
                url: https://schema.org/ccRecipient
              nullable: true
        bcc:
          type: array
          items:
            type: array
            items:
              example:
                - address: bcc@example.com
                  name: John Doe
              readOnly: true
              externalDocs:
                url: https://schema.org/bccRecipient
              nullable: true
        subject:
          readOnly: true
          externalDocs:
            url: https://schema.org/about
          type: string
        seen:
          type: boolean
        flagged:
          readOnly: true
          type: boolean
        isDeleted:
          type: boolean
        verifications:
          readOnly: true
          type: array
          items:
            type: string
        retention:
          type: boolean
        retentionDate:
          type: string
          format: date-time
        text:
          readOnly: true
          type: string
        html:
          readOnly: true
          type: array
          items:
            type: string
        hasAttachments:
          readOnly: true
          type: boolean
        attachments:
          type: array
          items:
            type: array
            items:
              example:
                - id: ATTACH000001
                  filename: happy.png
                  contentType: image/png
                  disposition: attachment
                  transferEncoding: base64
                  related: false
                  size: 666
                  downloadUrl: /messages/id/attachment/ATTACH000001
          externalDocs:
            url: https://schema.org/messageAttachment
        size:
          readOnly: true
          externalDocs:
            url: https://schema.org/fileSize
          type: integer
        downloadUrl:
          readOnly: true
          externalDocs:
            url: http://schema.org/contentUrl
          type: string
        createdAt:
          readOnly: true
          externalDocs:
            url: https://schema.org/dateSent
          type: string
          format: date-time
        updatedAt:
          readOnly: true
          externalDocs:
            url: https://schema.org/dateReceived
          type: string
          format: date-time
    Message-message.write:
      type: object
      description: ''
      properties:
        seen:
          type: boolean
    Message-messages.read:
      type: object
      description: ''
      properties:
        id:
          readOnly: true
          type: string
        accountId:
          readOnly: true
          type: string
          format: iri-reference
        msgid:
          readOnly: true
          type: string
        from:
          example:
          - address: from@example.com
            name: John Doe
          readOnly: true
          externalDocs:
            url: https://schema.org/sender
          type: array
          items:
            type: string
          nullable: true
        to:
          type: array
          items:
            type: array
            items:
              example:
                - address: receiver@example.com
                  name: John Doe
              readOnly: true
              externalDocs:
                url: https://schema.org/recipient
              nullable: true
        subject:
          readOnly: true
          externalDocs:
            url: https://schema.org/about
          type: string
        intro:
          readOnly: true
          externalDocs:
            url: https://schema.org/backstory
          type: string
        seen:
          type: boolean
        isDeleted:
          type: boolean
        hasAttachments:
          readOnly: true
          type: boolean
        size:
          readOnly: true
          externalDocs:
            url: https://schema.org/fileSize
          type: integer
        downloadUrl:
          readOnly: true
          externalDocs:
            url: http://schema.org/contentUrl
          type: string
        createdAt:
          readOnly: true
          externalDocs:
            url: https://schema.org/dateSent
          type: string
          format: date-time
        updatedAt:
          readOnly: true
          externalDocs:
            url: https://schema.org/dateReceived
          type: string
          format: date-time
    Source-source.read:
      type: object
      description: ''
      properties:
        id:
          readOnly: true
          type: string
        downloadUrl:
          type: string
        data:
          type: string
    Token:
      type: object
      properties:
        token:
          type: string
          readOnly: true
    Credentials:
      type: object
      properties:
        address:
          type: string
          example: test@example.com
        password:
          type: string
          example: password
  responses: {}
  parameters: {}
  examples: {}
  requestBodies: {}
  headers: {}
  securitySchemes:
    apiKey:
      type: apiKey
      in: header
      name: Authorization