server:
  port: ${PORT:8090}

spring:
  output:
    ansi:
      enabled: always

  datasource:
    driver: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  liquibase:
    enabled: false