server:
  port: ${PORT:8090}

spring:
  output:
    ansi:
      enabled: always

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

  liquibase:
    enabled: false